config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search", as: "search"
  get "tag_search" => "searches#tag_search", as: "tag_search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "follower" => "relationships#follower", as: "follower"
    get "search" => "users#search", as: "search"
  end

  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
    resources :room_enters, only: [:create]
  end

  resources :groups, only: [:index, :show, :new, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :view_counts, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }, presence: true


  def favorites_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(send_tags)
    send_tags.to_s.split(",").each do |send_tag|
      if Tag.find_by(name: send_tag).nil?
        Tag.create(name: send_tag)
      end
    end

    send_tags.to_s.split(",").each do |send_tag|
      tag = Tag.find_by(name: send_tag)
      BookTag.create(tag_id: tag.id, book_id: self.id)
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/book_tag.rb
class BookTag < ApplicationRecord

  belongs_to :tag
  belongs_to :book

  validates :book_id, presence: true
  validates :tag_id, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :user
  has_many :group_users, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 140 }

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_enters, dependent: :destroy
  has_many :rooms, through: :room_enters
  has_many :messages, dependent: :destroy
end

app/models/room_enter.rb
class RoomEnter < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :book_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :books, through: :book_tags

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :room_enters, dependent: :destroy
  has_many :rooms, through: :room_enters
  has_many :messages, dependent: :destroy

  has_many :view_counts, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,  length: { maximum: 50 }

  def relationships_by?(current_user, user)
    Relationship.find_by(follower_id: current_user.id, followed_id: user.id)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def post_count(from_day,to_day)
    self.books.where(created_at: (Time.zone.now.beginning_of_day - from_day.day)..(Time.zone.now.end_of_day - to_day.day)).count
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])

  end

  def new
    @group_new = Group.new
  end

  def create
    @group_new = Group.new(group_params)
    @group_new.user_id = current_user.id
    if @group_new.save
      group_user_new = GroupUser.new
      group_user_new.group_id = @group_new.id
      group_user_new.user_id = @group_new.user_id
      group_user_new.save
      redirect_to groups_path
      flash[:notice] = "グループを作成しました。"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
      flash[:notice] = "グループを編集しました。"
    else
      render :edit
    end

  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.user_id == current_user.id
      redirect_to groups_path
    end
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content,group_users).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class='container mt-5'>
	<div class='row'>
  	<div class='mx-auto'>
      <h2>EditingGroup</h2>
      <%= form_with model: @group, url: group_path, local: true, method: :patch do |form| %>
        <%= form.label :name, "グループ名" %><br>
        <%= form.text_field :name %>
        <br>
        <%= form.label :introduction, "紹介文" %><br>
        <%= form.text_area :introduction %><br>
        <br>
        <%= form.submit "UpdateGroup" %>
      <% end %>
  	</div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <h2 class="mt-3">New book</h2>


    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class="table">
        <thead>
          <tr>
            <td>グループ名</td>
            <td>紹介文</td>
            <td>メンバー数</td>
            <td>編集</td>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
          <tr>
            <td><%= link_to group.name, group_path(group.id) %></td>
            <td><%= group.introduction %></td>
            <td><%= group.group_users.count %></td>
            <td>
              <% if group.user_id == current_user.id %>
                <%= link_to "edit", edit_group_path(group.id) %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container mt-5'>
	<div class='row'>
  	<div class='mx-auto'>
      <h2>CreateGroup</h2>
      <%= form_with model: @group_new, url: groups_path, local: true, method: :post do |form| %>
        <%= form.label :name, "グループ名" %><br>
        <%= form.text_field :name %>
        <br>
        <%= form.label :introduction, "紹介文" %><br>
        <%= form.text_area :introduction %><br>
        <br>
        <%= form.submit "CreateGroup" %>
      <% end %>
  	</div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2><%=@group.name %>メンバーへのメール</h2>
    <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :mail_title,class:'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label:content %>
      <%= f.text_area :mail_content,class:'form-control' %>
    </div>
    <div>
      <%= f.submit'送信' %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
  <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <h2 class="mt-3">New book</h2>


    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>GroupDetails</h2>
      <table class="table">
        <thead>
          <tr>
            <td>グループ名</td>
            <td>紹介文</td>
            <td>メンバー</td>
            <td>編集</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <ul>
                <% @group.group_users.each do |group_user| %>
                  <li><%= group_user.user.name %></li>
                <% end %>
              </ul>
            </td>
            <td>
              <% if @group.user_id == current_user.id %>
                <%= link_to "edit", edit_group_path(@group.id) %>
              <% elsif @group.group_users.exists?(user_id: current_user.id) %>
                <%= link_to "Leave this group", group_group_users_path(@group.id), method: :delete %>
              <% else %>
                <%= link_to "Join this group", group_group_users_path(@group.id), method: :post %>
              <% end %>
            </td>
            <td>
              <% if @group.user_id == current_user.id %>
                <%= link_to 'Mail',group_new_mail_path(@group.id) %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>