config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search", as: "search"
  get "tag_search" => "searches#tag_search", as: "tag_search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "follower" => "relationships#follower", as: "follower"
    get "search" => "users#search", as: "search"
  end

  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
    resources :room_enters, only: [:create]
  end

  resources :groups, only: [:index, :show, :new, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :room_enters, dependent: :destroy
  has_many :rooms, through: :room_enters
  has_many :messages, dependent: :destroy

  has_many :view_counts, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,  length: { maximum: 50 }

  def relationships_by?(current_user, user)
    Relationship.find_by(follower_id: current_user.id, followed_id: user.id)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def post_count(from_day,to_day)
    self.books.where(created_at: (Time.zone.now.beginning_of_day - from_day.day)..(Time.zone.now.end_of_day - to_day.day)).count
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    current_room_enter = RoomEnter.where(user_id: current_user.id)
    another_room_enter = RoomEnter.where(user_id: @user.id)

    if current_user.id != @user.id
      current_room_enter.each do |c|
        another_room_enter.each do |a|
          if a.room_id == c.room_id
            @roomId = Room.find(c.room_id)
          end
        end
      end
    end

    @today_post_count = @user.books.where(created_at: (Time.zone.now.beginning_of_day)..(Time.zone.now.end_of_day)).count
    @yesterday_post_count = @user.books.where(created_at: (Time.zone.now.beginning_of_day - 1.day)..(Time.zone.now.end_of_day - 1.day)).count
    @this_week_post_count = @user.books.where(created_at: (Time.zone.now.beginning_of_day - 6.day)..(Time.zone.now.end_of_day)).count
    @last_week_post_count = @user.books.where(created_at: (Time.zone.now.beginning_of_day - 13.day)..(Time.zone.now.end_of_day - 7.day)).count

    if @yesterday_post_count = 0
      @day_before_ratio = "-"
    else
      @day_before_ratio = ((@today_post_count / @yesterday_post_count.to_f) * 100).floor
    end

    if @last_week_post_count = 0
      @week_before_ratio = "-"
    else
      @week_before_ratio = ((@this_week_post_count / @last_week_post_count.to_f) * 100).floor
    end
end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    search_day = params[:search_day]
    if search_day == ""
      @search_book = "日付を選択してください"
    else
      from = Time.parse(search_day).at_beginning_of_day
      to = Time.parse(search_day).at_end_of_day
      @search_book = Book.where(created_at: from..to).count
    end
  end


  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end

    def ensure_guest_user
      @user = User.find(params[:id])
      if @user.name == "guestuser"
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.active_relationships.count %></td>
        <td>フォロワー数：<%= user.passive_relationships.count %></td>
        <td><% if current_user.id != user.id %>
              <% if user.relationships_by?(current_user, user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
        </td><% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to user_following_path(user.id) do %>
	    <%= user.active_relationships.count %>
	    <% end %>
    </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to user_follower_path(user.id) do %>
	    <%= user.passive_relationships.count %>
	    <% end %>
    </th>
  </tr>
</table>

<% if current_user.id != user.id %>
<div class='row'>
  <% if user.relationships_by?(current_user, user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), class: "btn btn-sm btn-primary", method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-sm btn-success", method: :post %>
  <% end %>
</div>
<% end %>

<div class='row'>

<% if current_user.passive_relationships.exists?(user.active_relationships) %>
  <% if current_user.rooms.exists?(id: user.rooms) %>
    <% if @roomId.nil? %>

    <% else %>
      <%= link_to "チャットを送る", room_path(@roomId.id), class: "btn btn-sm btn-primary" %>
    <% end %>

  <% else %>
    <%= link_to "チャットを始める", rooms_path(user_id: user.id), class: "btn btn-sm btn-primary", method: :post %>
  <% end %>
<% end %>
</div>

<div class='row'>
  <% if user.id == current_user.id %>
    <% if user.name != "guestuser" %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h3>検索結果</h3>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= render 'layouts/errors', obj: @user %>

    <%= form_with model: @user, local:true do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>

    </div>
    <div class='col-md-8 offset-md-1'>


    <h2>Users</h2>
    <%= link_to "グループを作成する", new_group_path %>|<%= link_to "グループ一覧", groups_path %>

    <%= render 'searches/search_form' %>
    <%= render 'index',users: @users %>

    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= escape_javascript(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'books/ratio' %>
      <%= render 'books/graph',user: @user %>

      <%= form_with url: user_search_path(@user.id), local: false, method: :get do |form| %>
        <%= form.date_field :search_day %>
        <%= form.submit "検索" %>
      <% end %>

      <% @books.each do |book| %>
        作成日：<%= book.created_at %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>