config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search", as: "search"
  get "tag_search" => "searches#tag_search", as: "tag_search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "follower" => "relationships#follower", as: "follower"
    get "search" => "users#search", as: "search"
  end

  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
    resources :room_enters, only: [:create]
  end

  resources :groups, only: [:index, :show, :new, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :view_counts, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }, presence: true


  def favorites_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(send_tags)
    send_tags.to_s.split(",").each do |send_tag|
      if Tag.find_by(name: send_tag).nil?
        Tag.create(name: send_tag)
      end
    end

    send_tags.to_s.split(",").each do |send_tag|
      tag = Tag.find_by(name: send_tag)
      BookTag.create(tag_id: tag.id, book_id: self.id)
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/book_tag.rb
class BookTag < ApplicationRecord

  belongs_to :tag
  belongs_to :book

  validates :book_id, presence: true
  validates :tag_id, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :user
  has_many :group_users, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 140 }

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_enters, dependent: :destroy
  has_many :rooms, through: :room_enters
  has_many :messages, dependent: :destroy
end

app/models/room_enter.rb
class RoomEnter < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :book_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :books, through: :book_tags

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :room_enters, dependent: :destroy
  has_many :rooms, through: :room_enters
  has_many :messages, dependent: :destroy

  has_many :view_counts, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,  length: { maximum: 50 }

  def relationships_by?(current_user, user)
    Relationship.find_by(follower_id: current_user.id, followed_id: user.id)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def post_count(from_day,to_day)
    self.books.where(created_at: (Time.zone.now.beginning_of_day - from_day.day)..(Time.zone.now.end_of_day - to_day.day)).count
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model_selection = params[:model_selection]
    @retrieval_method = params[:retrieval_method]

    if @retrieval_method == "perfect_match"
      @word = "#{params[:word]}"
    elsif @retrieval_method == "forward_match"
      @word = "#{params[:word]}%"
    elsif @retrieval_method == "backward_match"
      @word = "%#{params[:word]}"
    elsif @retrieval_method == "partial_match"
      @word = "%#{params[:word]}%"
    end

    if @model_selection == "User"
      @users = User.where("name LIKE ?", "#{@word}").or(User.where("introduction LIKE ?", "#{@word}"))
    else
      @books = Book.where("title LIKE ?", "#{@word}").or(Book.where("body LIKE ?", "#{@word}"))
    end
  end

  def tag_search
    @tag = params[:tag]
    @books = Tag.find_by("name LIKE ?", "%#{@tag}%").books
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/_search_form.html.erb
<% if user_signed_in? %>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %>
        <%= f.select :model_selection, options_for_select([['User'],['Book']]) %>
        <%= f.select :retrieval_method, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/searches/_tag_search_form.html.erb
<% if user_signed_in? %>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
      <%= form_with url: tag_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :tag %>
        <%= f.submit "タグ検索" %>
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2><%= "#{@model_selection}s search for #{@word}" %></h2>

<% if @model_selection == "User" %>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>introduction</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
      <td><%= user.name %></td>
      <td><%= user.introduction %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<% else %>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>title</th>
      <th>opinion</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= image_tag book.user.get_profile_image, size:'50x50' %></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/searches/tag_search.html.erb
<h2>"<%= @tag %>"の検索結果</h2>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>title</th>
      <th>opinion</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= image_tag book.user.get_profile_image, size:'50x50' %></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td>
        <% book.tags.each do |tag| %>
          <%= link_to tag.name, tag_search_path(tag: tag.name) %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>